version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    command: "gunicorn --bind 0.0.0.0:5000 app:app"
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web