# Generated by Django 3.1.1 on 2022-09-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220902_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='approved',
        ),
    ]
